name: Build a container image
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta-binary
        with:
          images: ghcr.io/miscord-dev/rarejobctl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/metadata-action@v5
        id: meta-standalone
        with:
          images: ghcr.io/miscord-dev/rarejobctl-standalone
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: miscord-dev
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-binary.outputs.tags }}
          labels: ${{ steps.meta-binary.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-standalone
          push: true
          tags: ${{ steps.meta-standalone.outputs.tags }}
          labels: ${{ steps.meta-standalone.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
