name: Build a container image
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: meta-binary
        with:
          images: ghcr.io/musaprg/rarejobctl
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/metadata-action@v4
        id: meta-standalone
        with:
          images: ghcr.io/musaprg/rarejobctl-standalone
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: musaprg
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-binary.outputs.tags }}
          labels: ${{ steps.meta-binary.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-standalone
          push: true
          tags: ${{ steps.meta-standalone.outputs.tags }}
          labels: ${{ steps.meta-standalone.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
