name: Reserve next daily lesson
on:
  schedule:
    - cron: "0 12 * * *" # execute at every 21:00 (JST)
  workflow_dispatch:
jobs:
  reserve:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome-debug:3.141
    container:
      image: ghcr.io/musaprg/rarejobctl:latest
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        RAREJOB_EMAIL: ${{ secrets.RAREJOB_EMAIL }}
        RAREJOB_PASSWORD: ${{ secrets.RAREJOB_PASSWORD }}
    steps:
      - name: Reserve a next lesson
        env:
          TZ: "Asia/Tokyo" # Timezone is set to JST
        run: |
          export TOMORROW_YEAR=$(date -d'+1day' +'%-Y')
          export TOMORROW_MONTH=$(date -d'+1day' +'%-m')
          export TOMORROW_DAY_OF_MONTH=$(date -d'+1day' +'%-d')
          rarejobctl \
            -selenium-host selenium \
            -selenium-port 4444 \
            -selenium-browser-name chrome \
            -year ${TOMORROW_YEAR} \
            -month ${TOMORROW_MONTH} \
            -day ${TOMORROW_DAY_OF_MONTH} \
            -time "10:30" \
            -margin 0
